pipeline {
	agent any

    environment {
        EMAIL_TO = 'test@test.com'
    }

	triggers {
	  pollSCM 'H/5 * * * *'
	}

  stages {

    stage('checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/xonatis-academy/epsi-dev709-ci.git'
      }
    }

    stage('clean') {
      steps {
          dir('projects/erphrense') {
            bat './mvnw clean'
          }
          
      }
    }

    stage('compile') {
      steps {
          dir('projects/erphrense') {
            bat './mvnw compile'
          }
          
      }
    }

    stage('test') {
      steps {
          dir('projects/erphrense') {
            bat './mvnw test'
          }
          
      }
    }

    stage('package') {
      steps {
          dir('projects/erphrense') {
            bat './mvnw package'
          }
          
      }
    }
	
    stage('archive') {
      steps {
          dir('projects/erphrense') {
            bat 'rename target\\erphrense-0.0.1-SNAPSHOT.jar erphrense-%BUILD_NUMBER%.jar'
            archiveArtifacts artifacts: 'target\\erphrense-*.jar', followSymlinks: false
          }
          
      }
    }

  }

  post {
        success {
            emailext body: 'Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}', 
                    to: "${EMAIL_TO}", 
                    subject: 'Build in success in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
        failure {
            emailext body: 'Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}', 
                    to: "${EMAIL_TO}", 
                    subject: 'Build failed in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
        unstable {
            emailext body: 'Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}', 
                    to: "${EMAIL_TO}", 
                    subject: 'Unstable build in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
        changed {
            emailext body: 'Check console output at $BUILD_URL to view the results.', 
                    to: "${EMAIL_TO}", 
                    subject: 'Jenkins build is back to normal: $PROJECT_NAME - #$BUILD_NUMBER'
        }
    }
}